[formatter.ditto]
command = "ditto"
options = ["fmt"]
includes = ["*.ditto"]

[formatter.prettier]
command = "npx"
options = ["prettier", "--write"]
includes = ["*.js", "*.ts", "*.html", "*.json", "*.md", "*.yaml"]
